### PR TITLE
feat: Instance segmentation model

### PR DESCRIPTION
**Pull request by intsco**
* Move _segmentation_ to _semantic_segmentation_.
* Add _instance_segmentation_ example model (a dummy one).

Goes together with https://github.com/telesto-ai/telesto-base/pull/20 and https://github.com/telesto-ai/telesto-base/pull/22

@koosk I have added documentation to the base models (see PR #22 above).

### CODE REVIEW

**Review by cosmic-cortex — APPROVED** [review]

**Comment by intsco** [comment]
@cosmic-cortex Thanks for approving but before we merge this PR we need to add an example instance segmentation model.

**Comment by cosmic-cortex** [comment]
Can't we just use a dummy model?

**Comment by intsco** [comment]
>Can't we just use a dummy model?

@cosmic-cortex Do you suggest just to copy over this code from telesto-base to here?
https://github.com/telesto-ai/telesto-base/blob/develop/telesto/segmentation/model.py#L29

**Comment by koosk** [comment]
> > Can't we just use a dummy model?
> 
> @cosmic-cortex Do you suggest just to copy over this code from telesto-base to here?
> https://github.com/telesto-ai/telesto-base/blob/develop/telesto/segmentation/model.py#L29

I think that should be enough.
However, I had to think about for a minute or two what the variable names are for (x, y, w, h). Is it planned to update the docs, or maybe include docstring?

**Comment by cosmic-cortex** [comment]
> @cosmic-cortex Do you suggest just to copy over this code from telesto-base to here?
> https://github.com/telesto-ai/telesto-base/blob/develop/telesto/segmentation/model.py#L29

Yes, temporarily.

**Review by koosk — APPROVED** [review]

**Pull request merged**
